-- FEEC 100 Cims catalog, personal ascents and private photo storage.
create table public.summits (
  id text primary key,
  name text not null,
  height integer not null check (height > 0),
  region text not null,
  essential boolean not null default false,
  url text not null unique
);
alter table public.summits enable row level security;
grant select on public.summits to anon, authenticated;
create policy "Anyone can read the FEEC catalog" on public.summits for select to anon, authenticated using (true);

create table public.ascent_records (
  user_id uuid not null references auth.users(id) on delete cascade,
  summit_id text not null references public.summits(id) on delete cascade,
  completed_at date not null,
  photo_path text unique,
  created_at timestamptz not null default now(),
  primary key (user_id, summit_id)
);
create index ascent_records_user_completed_idx on public.ascent_records (user_id, completed_at desc);
alter table public.ascent_records enable row level security;
grant select, insert, update, delete on public.ascent_records to authenticated;
create policy "Users can read their own ascents" on public.ascent_records for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can add their own ascents" on public.ascent_records for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update their own ascents" on public.ascent_records for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Users can delete their own ascents" on public.ascent_records for delete to authenticated using ((select auth.uid()) = user_id);

insert into public.summits (id,name,height,region,essential,url) values
('alt-de-juclar','Alt de Juclar',2588,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/alt-de-juclar/'),
('alt-de-la-capa','Alt de la Capa',2573,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/alt-de-la-capa/'),
('alt-del-griu','Alt del Griu',2874,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/alt-del-griu/'),
('balandrau','Balandrau',2585,'Ripollès',true,'https://www.feec.cat/activitats/100-cims/cim/balandrau/'),
('bassegoda','Bassegoda',1373,'Alt Empordà, Garrotxa',true,'https://www.feec.cat/activitats/100-cims/cim/bassegoda/'),
('bastiments','Bastiments',2881,'Conflent, Ripollès',true,'https://www.feec.cat/activitats/100-cims/cim/bastiments/'),
('bellmunt','Bellmunt',1248,'Osona',true,'https://www.feec.cat/activitats/100-cims/cim/bellmunt/'),
('besiberri-nord','Besiberri Nord',3008,'Alta Ribagorça, Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/besiberri-nord/'),
('besiberri-del-sud','Besiberri Sud',3023,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/besiberri-del-sud/'),
('bony-de-la-pica-o-pica-dos','Bony de la Pica o Pica d’Os',2405,'Alt Urgell, Andorra',true,'https://www.feec.cat/activitats/100-cims/cim/bony-de-la-pica-o-pica-dos/'),
('cabrera','Cabrera',1308,'Garrotxa, Osona',true,'https://www.feec.cat/activitats/100-cims/cim/cabrera/'),
('cambra-dase','Cambra d’Ase',2750,'Cerdanya Nord',true,'https://www.feec.cat/activitats/100-cims/cim/cambra-dase/'),
('campirme','Campirme',2633,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/campirme/'),
('canigo','Canigó',2784,'Conflent',true,'https://www.feec.cat/activitats/100-cims/cim/canigo/'),
('cap-de-boumort','Cap de Boumort',2077,'Pallars Jussà',true,'https://www.feec.cat/activitats/100-cims/cim/cap-de-boumort/'),
('cap-de-broate','Cap de Broate',2741,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/cap-de-broate/'),
('cap-de-carreu','Cap de Carreu',1749,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/cap-de-carreu/'),
('cap-de-gelada','Cap de Gelada',2449,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/cap-de-gelada/'),
('cap-de-la-boixassa','Cap de la Boixassa',1820,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/cap-de-la-boixassa/'),
('cap-de-la-gallina-pelada','Cap de la Gallina Pelada',2321,'Berguedà',true,'https://www.feec.cat/activitats/100-cims/cim/cap-de-la-gallina-pelada/'),
('cap-de-pla-redon','Cap de Pla Redon',1846,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/cap-de-pla-redon/'),
('cap-del-verd','Cap del Verd',2284,'Alt Urgell, Berguedà, Solsonès',true,'https://www.feec.cat/activitats/100-cims/cim/cap-del-verd/'),
('carlit','Carlit',2921,'Cerdanya Nord',true,'https://www.feec.cat/activitats/100-cims/cim/carlit/'),
('caro','Caro',1441,'Baix Ebre',true,'https://www.feec.cat/activitats/100-cims/cim/caro/'),
('casamanya-nord','Casamanya Nord',2750,'Andorra',true,'https://www.feec.cat/activitats/100-cims/cim/casamanya-nord/'),
('castell-de-besora','Castell de Besora',1030,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/castell-de-besora/'),
('castell-de-bocs','Castell de Bocs',662,'Vallès Occidental',false,'https://www.feec.cat/activitats/100-cims/cim/castell-de-bocs/'),
('castell-de-boixadors','Castell de Boixadors',848,'Anoia',false,'https://www.feec.cat/activitats/100-cims/cim/castell-de-boixadors/'),
('castell-de-burriac','Castell de Burriac',392,'Maresme',true,'https://www.feec.cat/activitats/100-cims/cim/castell-de-burriac/'),
('castell-de-llivia','Castell de Llívia',1358,'Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/castell-de-llivia/'),
('castell-de-lluca','Castell de Lluçà',895,'Lluçanès ',false,'https://www.feec.cat/activitats/100-cims/cim/castell-de-lluca/'),
('castell-de-milany','Castell de Milany',1529,'Osona, Ripollès',true,'https://www.feec.cat/activitats/100-cims/cim/castell-de-milany/'),
('castell-de-montgri','Castell de Montgrí',303,'Baix Empordà',true,'https://www.feec.cat/activitats/100-cims/cim/castell-de-montgri/'),
('castell-de-sant-miquel','Castell de Sant Miquel',385,'Gironès',true,'https://www.feec.cat/activitats/100-cims/cim/castell-de-sant-miquel/'),
('castell-saverdera','Castell Saverdera',682,'Alt Empordà',true,'https://www.feec.cat/activitats/100-cims/cim/castell-saverdera/'),
('castellsapera','Castellsapera',939,'Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/castellsapera/'),
('catinell','Catinell',1350,'Baix Ebre, Montsià',false,'https://www.feec.cat/activitats/100-cims/cim/catinell/'),
('cavall-bernat-de-llaberia','Cavall Bernat de Llaberia',840,'Baix Camp',true,'https://www.feec.cat/activitats/100-cims/cim/cavall-bernat-de-llaberia/'),
('clapi-vell','Clapí Vell',703,'Alt Penedès',false,'https://www.feec.cat/activitats/100-cims/cim/clapi-vell/'),
('codol-del-castellar','Còdol del Castellar',832,'Moianès',false,'https://www.feec.cat/activitats/100-cims/cim/codol-del-castellar/'),
('cogullo-destela','Cogulló d’Estela',1870,'Berguedà',true,'https://www.feec.cat/activitats/100-cims/cim/cogullo-destela/'),
('cogullo-de-cal-torre','Cogulló de Cal Torre',881,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/cogullo-de-cal-torre/'),
('cogullo-de-turp','Cogulló de Turp',1621,'Alt Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/cogullo-de-turp/'),
('coll-de-pins','Coll de Pins',500,'Ribera d''Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/coll-de-pins/'),
('collbaix','Collbaix',543,'Bages',true,'https://www.feec.cat/activitats/100-cims/cim/collbaix/'),
('comabona','Comabona',2548,'Berguedà, Cerdanya',true,'https://www.feec.cat/activitats/100-cims/cim/comabona/'),
('comanegra','Comanegra',1557,'Garrotxa, Vallespir',true,'https://www.feec.cat/activitats/100-cims/cim/comanegra/'),
('comapedrosa','Comapedrosa',2942,'Andorra',true,'https://www.feec.cat/activitats/100-cims/cim/comapedrosa/'),
('costa-pubilla-o-pla-de-pujalts','Costa Pubilla o Pla de Pujalts',2056,'Ripollès',true,'https://www.feec.cat/activitats/100-cims/cim/costa-pubilla-o-pla-de-pujalts/'),
('costabona','Costabona',2465,'Ripollès, Vallespir',true,'https://www.feec.cat/activitats/100-cims/cim/costabona/'),
('creu-de-gurb','Creu de Gurb',842,'Osona',true,'https://www.feec.cat/activitats/100-cims/cim/creu-de-gurb/'),
('xaquera-o-creu-de-santos','Creu de Santos',942,'Baix Ebre, Ribera d''Ebre',true,'https://www.feec.cat/activitats/100-cims/cim/xaquera-o-creu-de-santos/'),
('el-bres','el Bres',525,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/el-bres/'),
('el-cadinell','El Cadinell',2113,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/el-cadinell/'),
('puig-castellar-serra-dancosa','El Castellar (serra d’Ancosa)',943,'Anoia',false,'https://www.feec.cat/activitats/100-cims/cim/puig-castellar-serra-dancosa/'),
('el-castellot','El Castellot',465,'Alt Penedès',true,'https://www.feec.cat/activitats/100-cims/cim/el-castellot/'),
('el-codo','el Codó',1327,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/el-codo/'),
('el-cogul','El Cogul',1526,'Solsonès',true,'https://www.feec.cat/activitats/100-cims/cim/el-cogul/'),
('el-cogullo','el Cogulló',1002,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/el-cogullo/'),
('el-cogullo-de-cabra','El Cogulló de Cabra',881,'Alt Camp',true,'https://www.feec.cat/activitats/100-cims/cim/el-cogullo-de-cabra/'),
('el-coscollet','El Coscollet',1610,'Alt Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/el-coscollet/'),
('el-far','El Far',1124,'Selva',false,'https://www.feec.cat/activitats/100-cims/cim/el-far/'),
('el-garrofi','el Garrofí',617,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/el-garrofi/'),
('el-mont','El Mont',1125,'Alt Empordà',true,'https://www.feec.cat/activitats/100-cims/cim/el-mont/'),
('el-montsianell','El Montsianell',293,'Montsià',false,'https://www.feec.cat/activitats/100-cims/cim/el-montsianell/'),
('el-negrell','El Negrell',1345,'Montsià',false,'https://www.feec.cat/activitats/100-cims/cim/el-negrell/'),
('el-punxo','el Punxó',2581,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/el-punxo/'),
('el-sui','el Sui',1319,'Vallès Oriental',false,'https://www.feec.cat/activitats/100-cims/cim/el-sui/'),
('el-torn','El Torn',152,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/el-torn/'),
('el-tossal-gros','El Tossal Gros',867,'Alt Camp, Conca de Barberà',true,'https://www.feec.cat/activitats/100-cims/cim/el-tossal-gros/'),
('els-angels','Els Àngels',483,'Gironès',true,'https://www.feec.cat/activitats/100-cims/cim/els-angels/'),
('els-bessons','Els Bessons',593,'Garrigues',true,'https://www.feec.cat/activitats/100-cims/cim/els-bessons/'),
('els-munts','Els Munts',1057,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/els-munts/'),
('els-quatre-mollons','els Quatre Mollons',433,'Montsià',false,'https://www.feec.cat/activitats/100-cims/cim/els-quatre-mollons/'),
('els-tossals','Els Tossals',1525,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/els-tossals/'),
('forca-real','Força Real',507,'Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/forca-real/'),
('gallinova','Gallinova',1687,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/gallinova/'),
('gra-de-fajol','Gra de Fajol',2714,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/gra-de-fajol/'),
('gran-encantat','Gran Encantat',2749,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/gran-encantat/'),
('gran-pic-del-pesso','Gran Pic del Pessó',2894,'Alta Ribagorça, Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/gran-pic-del-pesso/'),
('gran-tuc-de-colomers','Gran Tuc de Colomers',2933,'Alta Ribagorça, Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/gran-tuc-de-colomers/'),
('grony-de-miralles','Grony de Miralles',866,'Anoia',false,'https://www.feec.cat/activitats/100-cims/cim/grony-de-miralles/'),
('lalbarda-castellana','L’Albarda Castellana',1178,'Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/lalbarda-castellana/'),
('laliga','l’Àliga (Mola del Broi)',383,'Ribera d''Ebre, Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/laliga/'),
('largimon','L’Argimon',465,'Selva',false,'https://www.feec.cat/activitats/100-cims/cim/largimon/'),
('laut','l’Aüt',2532,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/laut/'),
('lavedoga-dadons','l’Avedoga d’Adons',1839,'Alta Ribagorça, Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/lavedoga-dadons/'),
('lenclusa','L’''´Enclusa',867,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/lenclusa/'),
('lespina','L’Espina',1181,'Baix Ebre, Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/lespina/'),
('loratori','l’Oratori',1757,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/loratori/'),
('la-carabassa','La Carabassa',2740,'Cerdanya',true,'https://www.feec.cat/activitats/100-cims/cim/la-carabassa/'),
('la-cogula','la Cogula',406,'Montsià',false,'https://www.feec.cat/activitats/100-cims/cim/la-cogula/'),
('la-cogulla','La Cogulla',786,'Alt Camp, Conca de Barberà',false,'https://www.feec.cat/activitats/100-cims/cim/la-cogulla/'),
('la-cogulla-montsant','La Cogulla (Montsant)',1062,'Priorat',false,'https://www.feec.cat/activitats/100-cims/cim/la-cogulla-montsant/'),
('la-coscollosa','La Coscollosa',879,'Baix Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/la-coscollosa/'),
('la-creueta','la Creueta',2067,'Berguedà, Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/la-creueta/'),
('la-faiada','La Faiada',1699,'Alta Ribagorça, Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/la-faiada/'),
('la-fita-alta','La Fita Alta',289,'Pla d''Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/la-fita-alta/'),
('la-guardia-serra-de-busa','la Guàrdia (Serra de Busa)',1448,'Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/la-guardia-serra-de-busa/'),
('la-miranda-de-terranyes','la Miranda de Terranyes',1193,'Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/la-miranda-de-terranyes/'),
('la-mola','La Mola',317,'Baix Penedès, Tarragonès',true,'https://www.feec.cat/activitats/100-cims/cim/la-mola/'),
('la-mola-de-sant-llorenc-del-munt','La Mola de Sant Llorenç del Munt',1102,'Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/la-mola-de-sant-llorenc-del-munt/'),
('la-moleta','la Moleta',812,'Baix Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/la-moleta/'),
('la-morella','La Morella',594,'Baix Llobregat',true,'https://www.feec.cat/activitats/100-cims/cim/la-morella/'),
('la-muga','La Muga',2861,'Cerdanya',true,'https://www.feec.cat/activitats/100-cims/cim/la-muga/'),
('la-picossa','La Picossa',499,'Ribera d''Ebre',true,'https://www.feec.cat/activitats/100-cims/cim/la-picossa/'),
('la-portella-del-pinell','la Portella del Pinell',1098,'Montsià',false,'https://www.feec.cat/activitats/100-cims/cim/la-portella-del-pinell/'),
('la-serra-vingrau','la Serra (Vingrau)',576,'Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/la-serra-vingrau/'),
('la-soca','la Soca',1635,'Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/la-soca/'),
('la-tosa','La Tosa',2536,'Berguedà, Cerdanya',true,'https://www.feec.cat/activitats/100-cims/cim/la-tosa/'),
('la-tossa-tivissa','La Tossa (Tivissa)',718,'Ribera d''Ebre',true,'https://www.feec.cat/activitats/100-cims/cim/la-tossa-tivissa/'),
('les-agudes','Les Agudes',1705,'Selva, Vallès Oriental',true,'https://www.feec.cat/activitats/100-cims/cim/les-agudes/'),
('les-borregues','Les Borregues',2693,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/les-borregues/'),
('les-carcoles','les Càrcoles',425,'Ribera d''Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/les-carcoles/'),
('les-picardes','les Picardes',2802,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/les-picardes/'),
('roca-de-la-barca-les-picossies','Les Picòssies',772,'Baix Ebre, Ribera d''Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/roca-de-la-barca-les-picossies/'),
('les-piques','Les Piques',1969,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/les-piques/'),
('les-solius','les Solius',533,'Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/les-solius/'),
('lo-blau-roca-grossa-moletans','lo Blau (Roca Grossa Moletans)',841,'Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/lo-blau-roca-grossa-moletans/'),
('lo-caramull','lo Caramull',429,'Baix Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/lo-caramull/'),
('lo-corrunco','Lo Corronco',2543,'Alta Ribagorça',true,'https://www.feec.cat/activitats/100-cims/cim/lo-corrunco/'),
('lo-morral','lo Morral',682,'Priorat',false,'https://www.feec.cat/activitats/100-cims/cim/lo-morral/'),
('lo-peladet','lo Peladet',1471,'Noguera, Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/lo-peladet/'),
('lo-tesol-teso-de-son','Lo Tésol (Tesó de Son)',2700,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/lo-tesol-teso-de-son/'),
('lo-tormo','Lo Tormo',523,'Ribera d''Ebre',true,'https://www.feec.cat/activitats/100-cims/cim/lo-tormo/'),
('los-picons','Los Picons',951,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/los-picons/'),
('malera','Malera',877,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/malera/'),
('malh-de-bolard','Malh de Bolard',2753,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/malh-de-bolard/'),
('malh-dera-artiga','Malh dera Artiga',2710,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/malh-dera-artiga/'),
('malh-des-pois-la-forcanada','Malh des Pois (la Forcanada)',2883,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/malh-des-pois-la-forcanada/'),
('matagalls','Matagalls',1697,'Osona, Vallès Oriental',true,'https://www.feec.cat/activitats/100-cims/cim/matagalls/'),
('mauberme','Maubèrme',2882,'Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/mauberme/'),
('mirador-del-pla-de-llet','Mirador del Pla de Llet',2141,'Alt Urgell, Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/mirador-del-pla-de-llet/'),
('miranda-de-llaberia','Miranda de Llaberia',919,'Baix Camp, Ribera d''Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/miranda-de-llaberia/'),
('miranda-de-puigcerver','Miranda de Puigcerver',834,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/miranda-de-puigcerver/'),
('miranda-de-santa-magdalena','Miranda de Santa Magdalena',1132,'Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/miranda-de-santa-magdalena/'),
('miranda-del-princep','Miranda del Príncep',993,'Anoia',false,'https://www.feec.cat/activitats/100-cims/cim/miranda-del-princep/'),
('miranda-dels-ecos','Miranda dels Ecos',1223,'Anoia',false,'https://www.feec.cat/activitats/100-cims/cim/miranda-dels-ecos/'),
('mola-castellona','Mola Castellona',1034,'Baix Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/mola-castellona/'),
('mola-destat','Mola d’Estat',1136,'Baix Camp, Conca de Barberà',true,'https://www.feec.cat/activitats/100-cims/cim/mola-destat/'),
('mola-dirto','Mola d’Irto',538,'Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/mola-dirto/'),
('mola-de-colldejou','Mola de Colldejou',922,'Baix Camp',true,'https://www.feec.cat/activitats/100-cims/cim/mola-de-colldejou/'),
('mola-de-genesies','Mola de Genesies',711,'Baix Camp, Ribera d''Ebre',true,'https://www.feec.cat/activitats/100-cims/cim/mola-de-genesies/'),
('mola-de-lord','Mola de Lord',1189,'Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/mola-de-lord/'),
('moleta-de-les-canals','Moleta de les Canals',1070,'Baix Ebre, Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/moleta-de-les-canals/'),
('mollo-puntaire','Molló Puntaire',727,'Baix Camp',true,'https://www.feec.cat/activitats/100-cims/cim/mollo-puntaire/'),
('mont-roig','Mont-roig',2864,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/mont-roig/'),
('mont-roig-cim-de-les-altures','Mont-roig (Cim de les Altures)',715,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/mont-roig-cim-de-les-altures/'),
('montagut-dancosa','Montagut d’Ancosa',963,'Alt Camp',false,'https://www.feec.cat/activitats/100-cims/cim/montagut-dancosa/'),
('montalt','Montalt',597,'Maresme',true,'https://www.feec.cat/activitats/100-cims/cim/montalt/'),
('montalt-punta-nord','Montalt (punta nord)',766,'Priorat, Ribera d''Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/montalt-punta-nord/'),
('montanha-duishera','Montanha d’Uishèra',2339,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/montanha-duishera/'),
('montardo','Montardo',2833,'Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/montardo/'),
('montarenyo-de-boldis','Montarenyo de Boldís',2593,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/montarenyo-de-boldis/'),
('montaspre','Montaspre',528,'Baix Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/montaspre/'),
('montau','Montau',658,'Alt Penedès, Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/montau/'),
('montbarbat','Montbarbat',328,'Maresme, Selva',false,'https://www.feec.cat/activitats/100-cims/cim/montbarbat/'),
('montcau','Montcau',1057,'Bages, Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/montcau/'),
('montcaubo-lo-calbo','Montcaubo (lo Calbo)',2291,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/montcaubo-lo-calbo/'),
('montclar','Montclar',401,'Baix Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/montclar/'),
('montcorbison','Montcorbison',2173,'Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/montcorbison/'),
('monteixo','Monteixo',2905,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/monteixo/'),
('montero','Monteró',574,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/montero/'),
('montgros','Montgròs',1133,'Anoia',true,'https://www.feec.cat/activitats/100-cims/cim/montgros/'),
('montigalar','Montigalar',464,'Gironès',false,'https://www.feec.cat/activitats/100-cims/cim/montigalar/'),
('montllobar','Montllobar',1104,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/montllobar/'),
('montlude','Montlude',2518,'Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/montlude/'),
('montmagastre','Montmagastre',762,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/montmagastre/'),
('montmajor','Montmajor',1074,'Garrotxa',false,'https://www.feec.cat/activitats/100-cims/cim/montmajor/'),
('montmalus','Montmalús',2781,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/montmalus/'),
('montolier-de-perellos','Montolier de Perellós',707,'Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/montolier-de-perellos/'),
('montpalau','Montpalau',264,'Maresme',false,'https://www.feec.cat/activitats/100-cims/cim/montpalau/'),
('montsaliente','Montsaliente',2890,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/montsaliente/'),
('montsent-serrat-de-picancel','Montsent (Serrat de Picancel)',963,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/montsent-serrat-de-picancel/'),
('montsent-de-pallars','Montsent de Pallars',2883,'Pallars Jussà, Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/montsent-de-pallars/'),
('monturull','Monturull',2760,'Alt Urgell, Andorra, Cerdanya',true,'https://www.feec.cat/activitats/100-cims/cim/monturull/'),
('morral-del-cabrafeixet','Morral del Cabrafeixet',753,'Baix Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/morral-del-cabrafeixet/'),
('munt-de-montsonis','Munt de Montsonís',591,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/munt-de-montsonis/'),
('noufonts','Noufonts',2861,'Conflent, Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/noufonts/'),
('pala-alta','Pala Alta',947,'Noguera',true,'https://www.feec.cat/activitats/100-cims/cim/pala-alta/'),
('pala-del-teller','Pala del Teller',1889,'Alta Ribagorça, Pallars Jussà',true,'https://www.feec.cat/activitats/100-cims/cim/pala-del-teller/'),
('pedracastell-o-creu-de-canet','Pedracastell o Creu de Canet',287,'Maresme',false,'https://www.feec.cat/activitats/100-cims/cim/pedracastell-o-creu-de-canet/'),
('pedro-de-tubau','Pedró de Tubau',1543,'Berguedà, Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/pedro-de-tubau/'),
('pedro-dels-quatre-batlles','Pedró dels Quatre Batlles',2387,'Alt Urgell, Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/pedro-dels-quatre-batlles/'),
('penya-aguda','Penya Aguda',1523,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/penya-aguda/'),
('penya-del-papiol','Penya del Papiol',381,'Alt Penedès',true,'https://www.feec.cat/activitats/100-cims/cim/penya-del-papiol/'),
('penya-sant-alis','Penya Sant Alís',1675,'Noguera, Pallars Jussà',true,'https://www.feec.cat/activitats/100-cims/cim/penya-sant-alis/'),
('penyes-altes','Penyes Altes',2276,'Berguedà, Cerdanya',true,'https://www.feec.cat/activitats/100-cims/cim/penyes-altes/'),
('pic-alt-del-cubil','Pic Alt del Cubil',2834,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-alt-del-cubil/'),
('pic-descobes','Pic d’Escobes',2780,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-descobes/'),
('pic-de-baborte','Pic de Baborte',2934,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-baborte/'),
('pic-de-baixollada','Pic de Baixollada',2546,'Capcir',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-baixollada/'),
('pic-de-cabanyo','Pic de Cabanyó',2732,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-cabanyo/'),
('pic-de-canalbona','Pic de Canalbona',2965,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-canalbona/'),
('pic-de-cataperdis','Pic de Cataperdís',2805,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-cataperdis/'),
('pic-de-certascan','Pic de Certascan',2853,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/pic-de-certascan/'),
('pic-de-clavera','Pic de Clavera',2721,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-clavera/'),
('pic-de-colatx','Pic de Colatx',2570,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-colatx/'),
('pic-de-coma-mitjana','Pic de Coma Mitjana',2732,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-coma-mitjana/'),
('pic-de-comaloforno','Pic de Comaloforno',3029,'Alta Ribagorça',true,'https://www.feec.cat/activitats/100-cims/cim/pic-de-comaloforno/'),
('pic-de-contraix','Pic de Contraix',2958,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-contraix/'),
('pic-de-costa-cabirolera','Pic de Costa Cabirolera',2604,'Alt Urgell, Berguedà, Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-costa-cabirolera/'),
('pic-de-filia-tossal-de-paiasso','Pic de Filià (Tossal de Paiasso)',2772,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-filia-tossal-de-paiasso/'),
('pic-de-flamisella','Pic de Flamisella',2782,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-flamisella/'),
('pic-de-font-blanca','Pic de Font Blanca',2903,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-font-blanca/'),
('pic-de-font-freda','Pic de Font Freda',2738,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-font-freda/'),
('pic-de-gallinassa','Pic de Gallinassa',2461,'Conflent, Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-gallinassa/'),
('pic-de-gerri','Pic de Gerri',2859,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-gerri/'),
('pic-de-laguila','Pic de l’Àguila',492,'Ribera d''Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-laguila/'),
('pic-de-lespada','Pic de l’Espada',2549,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-lespada/'),
('pic-de-lestanyo','Pic de l’Estanyó',2915,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-lestanyo/'),
('pic-de-linfern','Pic de l’Infern',2870,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-linfern/'),
('pic-de-la-coma-de-varilles','Pic de la Coma de Varilles',2760,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-la-coma-de-varilles/'),
('pic-de-la-mainera','Pic de la Mainera',2909,'Pallars Jussà, Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-la-mainera/'),
('pic-de-la-pala-alta-de-sarrade','Pic de la Pala Alta de Sarradé',2983,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-la-pala-alta-de-sarrade/'),
('pic-de-la-plana','Pic de la Plana',2493,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-la-plana/'),
('pic-de-la-serrera','Pic de la Serrera',2912,'Andorra',true,'https://www.feec.cat/activitats/100-cims/cim/pic-de-la-serrera/'),
('pic-de-llena','Pic de Llena',2686,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-llena/'),
('pic-de-maniga','Pic de Màniga',2517,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-maniga/'),
('pic-de-mariola','Pic de Mariola',2663,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-mariola/'),
('pic-de-mariolo-pic-de-neriolo','Pic de Mariolo (Pic de Neriolo)',2857,'Alta Ribagorça, Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-mariolo-pic-de-neriolo/'),
('pic-de-medacorba','Pic de Medacorba',2915,'Andorra, Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-medacorba/'),
('pic-de-montalt','Pic de Montalt',2496,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-montalt/'),
('pic-de-moredo','Pic de Moredo',2766,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/pic-de-moredo/'),
('pic-de-peguera','Pic de Peguera',2983,'Pallars Jussà, Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/pic-de-peguera/'),
('pic-de-pilas','Pic de Pilàs',2656,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-pilas/'),
('pic-de-quenca','Pic de Qüenca',2639,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-quenca/'),
('pic-de-raco-gros','Pic de Racó Gros',2782,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-raco-gros/'),
('pic-de-saboredo','Pic de Saboredo',2830,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-saboredo/'),
('pic-de-sallafort','Pic de Sallafort',994,'Alt Empordà, Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-sallafort/'),
('pic-de-saloria','Pic de Salòria',2789,'Alt Urgell, Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/pic-de-saloria/'),
('pic-de-sanfonts','Pic de Sanfonts',2889,'Andorra, Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-sanfonts/'),
('pic-de-sotllo','Pic de Sotllo',3073,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/pic-de-sotllo/'),
('pic-de-subenuix','Pic de Subenuix',2950,'Pallars Jussà, Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-subenuix/'),
('pic-de-ventolau','Pic de Ventolau',2851,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-ventolau/'),
('pic-del-pla-de-lestany','Pic del Pla de l’Estany',2860,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-del-pla-de-lestany/'),
('pic-del-portarro','Pic del Portarró',2734,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-del-portarro/'),
('pic-del-vent','Pic del Vent',816,'Vallès Oriental',true,'https://www.feec.cat/activitats/100-cims/cim/pic-del-vent/'),
('pic-dels-moros','Pic dels Moros',2137,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/pic-dels-moros/'),
('pic-dels-pedrons','Pic dels Pedrons',2715,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/pic-dels-pedrons/'),
('pic-dels-pessons-o-gargantillar','Pic dels Pessons o Gargantillar',2862,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/pic-dels-pessons-o-gargantillar/'),
('pic-negre-denvalira','Pic Negre d’Envalira',2822,'Andorra, Cerdanya Nord',true,'https://www.feec.cat/activitats/100-cims/cim/pic-negre-denvalira/'),
('pic-roi','Pic Roi',2585,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/pic-roi/'),
('pic-tort','Pic Tort',2886,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/pic-tort/'),
('pica-destats','Pica d’Estats',3144,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/pica-destats/'),
('pica-de-cervi','Pica de Cerví',2753,'Pallars Jussà',true,'https://www.feec.cat/activitats/100-cims/cim/pica-de-cervi/'),
('pica-roja','Pica Roja',2903,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pica-roja/'),
('picorandan','Picorandan',991,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/picorandan/'),
('pics-de-bassiero','Pics de Bassiero (Occidental)',2903,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pics-de-bassiero/'),
('pilar-dalmenara','Pilar d’Almenara',459,'Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/pilar-dalmenara/'),
('pilo-de-bellmaig','Piló de Bellmaig',1281,'Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/pilo-de-bellmaig/'),
('pollego-inferior-pedraforca','Pollegó Inferior (Pedraforca)',2445,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/pollego-inferior-pedraforca/'),
('pollego-superior-pedraforca','Pollegó Superior (Pedraforca)',2506,'Berguedà',true,'https://www.feec.cat/activitats/100-cims/cim/pollego-superior-pedraforca/'),
('pui-durdosa','Pui d’Urdosa',2226,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pui-durdosa/'),
('pui-de-cassibros','Pui de Cassibrós',2085,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pui-de-cassibros/'),
('pui-de-la-bonaigua','Pui de la Bonaigua',2778,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pui-de-la-bonaigua/'),
('pui-de-linya','Pui de Linya',2870,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pui-de-linya/'),
('pui-de-lleras','Pui de Lleràs',1692,'Pallars Jussà',true,'https://www.feec.cat/activitats/100-cims/cim/pui-de-lleras/'),
('pui-tabaca','Pui Tabaca',1718,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/pui-tabaca/'),
('puig-cadiretes','Puig Cadiretes',519,'Gironès, Selva',false,'https://www.feec.cat/activitats/100-cims/cim/puig-cadiretes/'),
('puig-castellar','Puig Castellar',303,'Barcelonès, Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/puig-castellar/'),
('puig-cavaller','Puig Cavaller',706,'Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/puig-cavaller/'),
('puig-cendros','Puig Cendrós',499,'Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/puig-cendros/'),
('puig-clara','Puig Clarà',315,'Pla de l''Estany',false,'https://www.feec.cat/activitats/100-cims/cim/puig-clara/'),
('puig-cornador','Puig Cornador',1229,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-cornador/'),
('puig-cubell','Puig Cubell',1488,'Garrotxa, Osona',false,'https://www.feec.cat/activitats/100-cims/cim/puig-cubell/'),
('puig-daguilera','Puig d’Aguilera',626,'Anoia',false,'https://www.feec.cat/activitats/100-cims/cim/puig-daguilera/'),
('puig-dagulles','Puig d’Agulles',653,'Alt Penedès, Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/puig-dagulles/'),
('puig-darques','Puig d’Arques',533,'Baix Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-darques/'),
('puig-den-cama','Puig d’en Cama',717,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/puig-den-cama/'),
('puig-den-jorda','Puig d’en Jordà',754,'Alt Empordà, Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/puig-den-jorda/'),
('puig-desquers','Puig d’Esquers',606,'Alt Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-desquers/'),
('puig-dolorda','Puig d’Olorda',436,'Baix Llobregat, Barcelonès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-dolorda/'),
('puig-de-bestreca','Puig de Bestracà',1056,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-bestreca/'),
('puig-de-cervera','Puig de Cervera',207,'Alt Empordà, Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-cervera/'),
('pic-de-coma-dor','Puig de Coma d’Or',2826,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-coma-dor/'),
('puig-de-dorria','Puig de Dòrria',2547,'Cerdanya Nord, Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-dorria/'),
('puig-de-font-viva','Puig de Font Viva',2673,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-font-viva/'),
('puig-de-gallicant','Puig de Gallicant',1010,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-gallicant/'),
('puig-de-gallinas','Puig de Gallinàs',2624,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-gallinas/'),
('puig-de-grialo','Puig de Grialó',667,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-grialo/'),
('puig-de-laliga','Puig de l’Àliga',464,'Alt Penedès, Garraf',true,'https://www.feec.cat/activitats/100-cims/cim/puig-de-laliga/'),
('puig-de-laliga-cap-de-creus','Puig de l’Àliga (Cap de Creus)',463,'Alt Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-laliga-cap-de-creus/'),
('puig-de-lestella','Puig de l’Estella',1778,'Conflent, Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-lestella/'),
('puig-de-la-cabrafiga','Puig de la Cabrafiga',614,'Baix Camp',true,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-cabrafiga/'),
('puig-de-la-caritat','Puig de la Caritat',1010,'Moianès',true,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-caritat/'),
('puig-de-la-collada-verda','Puig de la Collada Verda',2403,'Conflent, Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-collada-verda/'),
('puig-de-la-cometa','Puig de la Cometa',2763,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-cometa/'),
('puig-de-la-cova','Puig de la Cova',672,'Baix Penedès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-cova/'),
('puig-de-la-creu','Puig de la Creu',668,'Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-creu/'),
('puig-de-la-forca','Puig de la Força',740,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-forca/'),
('puig-de-la-gavarra','Puig de la Gavarra',1057,'Alt Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-gavarra/'),
('puig-de-la-grava','Puig de la Grava',2671,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-grava/'),
('puig-de-la-mola','Puig de la Mola',534,'Alt Penedès, Baix Llobregat, Garraf',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-mola/'),
('puig-de-la-pelada','Puig de la Pelada',2370,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-la-pelada/'),
('puig-de-les-agudes','Puig de les Agudes',1976,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-les-agudes/'),
('puig-de-les-aligues','Puig de les Àligues',1344,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-les-aligues/'),
('puig-de-les-bruixes','Puig de les Bruixes',1391,'Alt Empordà, Garrotxa',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-les-bruixes/'),
('puig-de-les-cols','Puig de les Cols',417,'Baix Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-les-cols/'),
('puig-de-les-morreres','Puig de les Morreres',2211,'Solsonès',true,'https://www.feec.cat/activitats/100-cims/cim/puig-de-les-morreres/'),
('puig-de-les-tres-esteles','Puig de les Tres Esteles',2099,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-les-tres-esteles/'),
('puig-de-milla','Puig de Millà',1025,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-milla/'),
('puig-de-sant-antoni','Puig de Sant Antoni',409,'Baix Penedès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-sant-antoni/'),
('puig-de-sant-cristau','Puig de Sant Cristau',1015,'Rosselló, Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/puig-de-sant-cristau/'),
('puig-de-sant-miquel','Puig de Sant Miquel',733,'Anoia',true,'https://www.feec.cat/activitats/100-cims/cim/puig-de-sant-miquel/'),
('puig-de-tretzevents','Puig de Tretzevents',2731,'Conflent, Vallespir',true,'https://www.feec.cat/activitats/100-cims/cim/puig-de-tretzevents/'),
('puig-del-far','Puig del Far',832,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/puig-del-far/'),
('puig-del-pam','Puig del Pam',2470,'Capcir',false,'https://www.feec.cat/activitats/100-cims/cim/puig-del-pam/'),
('puig-dels-bufadors','Puig dels Bufadors',432,'Alt Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-dels-bufadors/'),
('puig-dels-pruners','Puig dels Pruners',832,'Alt Empordà, Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/puig-dels-pruners/'),
('puig-estela','Puig Estela',2013,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-estela/'),
('puig-falco','Puig Falcó',1097,'Alt Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-falco/'),
('puig-francas','Puig Francàs',551,'Baix Penedès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-francas/'),
('puig-gros','Puig Gros',325,'Baix Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-gros/'),
('puig-madrona','Puig Madrona',341,'Baix Llobregat, Vallès Occidental',false,'https://www.feec.cat/activitats/100-cims/cim/puig-madrona/'),
('puig-neulos','Puig Neulós',1257,'Alt Empordà, Rosselló',true,'https://www.feec.cat/activitats/100-cims/cim/puig-neulos/'),
('puig-occidental-de-coll-roig','Puig Occidental de Coll Roig',2833,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/puig-occidental-de-coll-roig/'),
('puig-ou','Puig Ou',1300,'Garrotxa, Ripollès',true,'https://www.feec.cat/activitats/100-cims/cim/puig-ou/'),
('puig-pedros-de-lanos','Puig Pedrós de Lanós',2842,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/puig-pedros-de-lanos/'),
('puig-pelat','Puig Pelat',1076,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/puig-pelat/'),
('puig-peric','Puig Peric',2810,'Capcir, Cerdanya Nord',true,'https://www.feec.cat/activitats/100-cims/cim/puig-peric/'),
('puig-segalar','Puig Segalar',175,'Alt Empordà, Baix Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/puig-segalar/'),
('puig-sobira','Puig Sobirà',1938,'Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/puig-sobira/'),
('puig-vicenc','Puig Vicenç',468,'Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/puig-vicenc/'),
('puig-alter','Puig-alter',522,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/puig-alter/'),
('puigcabrer','Puigcabrer',524,'Alt Camp',false,'https://www.feec.cat/activitats/100-cims/cim/puigcabrer/'),
('puigdefrou','Puigdefrou',839,'Selva',false,'https://www.feec.cat/activitats/100-cims/cim/puigdefrou/'),
('puiggracios','Puiggraciós',808,'Vallès Oriental',false,'https://www.feec.cat/activitats/100-cims/cim/puiggracios/'),
('puigllancada','Puigllançada',2409,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/puigllancada/'),
('puigmal','Puigmal',2910,'Cerdanya Nord, Ripollès',true,'https://www.feec.cat/activitats/100-cims/cim/puigmal/'),
('puigpedros','Puigpedrós',2915,'Cerdanya, Cerdanya Nord',true,'https://www.feec.cat/activitats/100-cims/cim/puigpedros/'),
('puigsacalm','Puigsacalm',1514,'Garrotxa',true,'https://www.feec.cat/activitats/100-cims/cim/puigsacalm/'),
('puigsallanca','Puigsallança',1027,'Garrotxa',false,'https://www.feec.cat/activitats/100-cims/cim/puigsallanca/'),
('puigsoler','Puigsoler',524,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/puigsoler/'),
('pujoalbo','Pujoalbo',2504,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/pujoalbo/'),
('pujol-de-la-mata','Pujol de la Mata',770,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/pujol-de-la-mata/'),
('punta-alta','Punta Alta',3014,'Alta Ribagorça',true,'https://www.feec.cat/activitats/100-cims/cim/punta-alta/'),
('punta-dharle','Punta d’Harlé',2885,'Alta Ribagorça, Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/punta-dharle/'),
('punta-dossos','Punta d’Ossos',1014,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/punta-dossos/'),
('punta-de-laigua','Punta de l’Aigua',1092,'Baix Ebre, Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/punta-de-laigua/'),
('montmeneu','Punta de Montmeneu',495,'Segrià',true,'https://www.feec.cat/activitats/100-cims/cim/montmeneu/'),
('punta-del-curull','Punta del Curull',1022,'Conca de Barberà, Garrigues',true,'https://www.feec.cat/activitats/100-cims/cim/punta-del-curull/'),
('punta-del-general','Punta del General',923,'Garrigues, Priorat',false,'https://www.feec.cat/activitats/100-cims/cim/punta-del-general/'),
('punta-del-pallars','Punta del Pallars',551,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/punta-del-pallars/'),
('punta-dels-pins-carrassers','Punta dels Pins Carrassers',1062,'Priorat',false,'https://www.feec.cat/activitats/100-cims/cim/punta-dels-pins-carrassers/'),
('punta-redona','Punta Redona',659,'Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/punta-redona/'),
('punta-senyalada','Punta Senyalada',2952,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/punta-senyalada/'),
('quermany-gros','Quermany Gros',228,'Baix Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/quermany-gros/'),
('querroig','Querroig',672,'Alt Empordà, Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/querroig/'),
('roc-beneidor','Roc Beneïdor',1681,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/roc-beneidor/'),
('roc-de-cogul','Roc de Cogul',885,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/roc-de-cogul/'),
('roc-de-galliner','Roc de Galliner',1630,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/roc-de-galliner/'),
('roc-de-les-monges-serrat-de-la-questio','Roc de les Monges (Serrat de la Qüestió)',1415,'Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/roc-de-les-monges-serrat-de-la-questio/'),
('roc-de-les-tres-creus','Roc de les Tres Creus',854,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/roc-de-les-tres-creus/'),
('roc-de-madres','Roc de Madres',2469,'Conflent',true,'https://www.feec.cat/activitats/100-cims/cim/roc-de-madres/'),
('roc-de-mallorca','Roc de Mallorca',443,'Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/roc-de-mallorca/'),
('roc-de-sant-aventi','Roc de Sant Aventí',1480,'Pallars Jussà, Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/roc-de-sant-aventi/'),
('roc-de-sant-salvador','Roc de Sant Salvador',1235,'Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/roc-de-sant-salvador/'),
('roc-del-boc','Roc del Boc',2774,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/roc-del-boc/'),
('roc-del-comptador','Roc del Comptador',1451,'Alt Empordà, Vallespir',true,'https://www.feec.cat/activitats/100-cims/cim/roc-del-comptador/'),
('roc-del-migdia-la-valldan','Roc del Migdia (la Valldan)',1153,'Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/roc-del-migdia-la-valldan/'),
('roc-mele','Roc Melé',2811,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/roc-mele/'),
('roc-roi','Roc Roi',2020,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/roc-roi/'),
('roca-colom','Roca Colom',2506,'Conflent, Ripollès, Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/roca-colom/'),
('roca-corbatera','Roca Corbatera',1163,'Priorat',true,'https://www.feec.cat/activitats/100-cims/cim/roca-corbatera/'),
('roca-de-migdia-serra-del-verd','Roca de Migdia (Serra del Verd)',1870,'Alt Urgell, Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/roca-de-migdia-serra-del-verd/'),
('roca-de-sant-salvador-lelefant','Roca de Sant Salvador (l’Elefant)',1156,'Bages',true,'https://www.feec.cat/activitats/100-cims/cim/roca-de-sant-salvador-lelefant/'),
('roca-del-coscollo','Roca del Coscolló',1299,'Alt Urgell, Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/roca-del-coscollo/'),
('roca-del-joc-roca-de-la-devesa-jussana','Roca del Joc (Roca de la Devesa Jussana)',1615,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/roca-del-joc-roca-de-la-devesa-jussana/'),
('roca-entravessada','Roca Entravessada',2929,'Andorra, Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/roca-entravessada/'),
('roca-gelera','Roca Gelera',1110,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/roca-gelera/'),
('roca-gran','Roca Gran',2088,'Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/roca-gran/'),
('roca-lladre','Roca Lladre',907,'Garrotxa',false,'https://www.feec.cat/activitats/100-cims/cim/roca-lladre/'),
('roca-maura','Roca Maura',225,'Baix Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/roca-maura/'),
('roca-roja','Roca Roja',1239,'Noguera, Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/roca-roja/'),
('roca-sareny','Roca Sareny',804,'Bages, Vallès Occidental',false,'https://www.feec.cat/activitats/100-cims/cim/roca-sareny/'),
('rocallarga','Rocallarga',1187,'Osona',true,'https://www.feec.cat/activitats/100-cims/cim/rocallarga/'),
('rocalta','Rocalta',1489,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/rocalta/'),
('rocamala','Rocamala',621,'Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/rocamala/'),
('roques-de-benet-el-castell','Roques de Benet (el Castell)',1017,'Terra Alta',true,'https://www.feec.cat/activitats/100-cims/cim/roques-de-benet-el-castell/'),
('roques-del-rei','Roques del Rei',852,'Selva',false,'https://www.feec.cat/activitats/100-cims/cim/roques-del-rei/'),
('salga-aguda','Salga Aguda',1172,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/salga-aguda/'),
('sant-antoni','Sant Antoni',1361,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/sant-antoni/'),
('sant-benet','Sant Benet',1150,'Selva',false,'https://www.feec.cat/activitats/100-cims/cim/sant-benet/'),
('sant-corneli','Sant Corneli',1351,'Pallars Jussà',true,'https://www.feec.cat/activitats/100-cims/cim/sant-corneli/'),
('sant-grau','Sant Grau',500,'Gironès',false,'https://www.feec.cat/activitats/100-cims/cim/sant-grau/'),
('sant-honorat','Sant Honorat',1068,'Alt Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/sant-honorat/'),
('sant-jeroni','Sant Jeroni',1236,'Anoia, Bages',true,'https://www.feec.cat/activitats/100-cims/cim/sant-jeroni/'),
('sant-mamet','Sant Mamet',1391,'Noguera',true,'https://www.feec.cat/activitats/100-cims/cim/sant-mamet/'),
('sant-marc-de-broca','Sant Marc de Brocà',1611,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/sant-marc-de-broca/'),
('sant-marti-de-la-roca','Sant Martí de la Roca',522,'Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/sant-marti-de-la-roca/'),
('sant-marti-xic-castell-de-voltrega','Sant Martí Xic (Castell de Voltregà)',859,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/sant-marti-xic-castell-de-voltrega/'),
('sant-miquel-de-montclar','Sant Miquel de Montclar',948,'Conca de Barberà',true,'https://www.feec.cat/activitats/100-cims/cim/sant-miquel-de-montclar/'),
('sant-miquel-de-solterra','Sant Miquel de Solterra',1203,'Selva',true,'https://www.feec.cat/activitats/100-cims/cim/sant-miquel-de-solterra/'),
('sant-miquel-del-mont','Sant Miquel del Mont',793,'Garrotxa',false,'https://www.feec.cat/activitats/100-cims/cim/sant-miquel-del-mont/'),
('sant-patllari','Sant Patllari',646,'Pla de l''Estany',true,'https://www.feec.cat/activitats/100-cims/cim/sant-patllari/'),
('sant-pere-martir','Sant Pere Màrtir',389,'Baix Llobregat, Barcelonès',true,'https://www.feec.cat/activitats/100-cims/cim/sant-pere-martir/'),
('sant-quiri','Sant Quiri',1503,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/sant-quiri/'),
('sant-ramon','Sant Ramon',295,'Baix Llobregat',true,'https://www.feec.cat/activitats/100-cims/cim/sant-ramon/'),
('sant-roc','Sant Roc',598,'Garrotxa, Gironès, Selva',false,'https://www.feec.cat/activitats/100-cims/cim/sant-roc/'),
('sant-sadurni-de-gallifa','Sant Sadurní de Gallifa',942,'Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/sant-sadurni-de-gallifa/'),
('sant-salvador','Sant Salvador',1157,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/sant-salvador/'),
('sant-salvador-de-les-espases','Sant Salvador de les Espases',413,'Baix Llobregat, Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/sant-salvador-de-les-espases/'),
('sant-simplici','Sant Simplici',110,'Tarragonès',false,'https://www.feec.cat/activitats/100-cims/cim/sant-simplici/'),
('santa-anna-dels-quatre-termes','Santa Anna dels Quatre Termes',1348,'Conflent, Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/santa-anna-dels-quatre-termes/'),
('santa-barbara','Santa Bàrbara',752,'Terra Alta',true,'https://www.feec.cat/activitats/100-cims/cim/santa-barbara/'),
('santa-barbara-escornalbou','Santa Bàrbara (Escornalbou)',641,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/santa-barbara-escornalbou/'),
('santa-barbara-vall-fosca','Santa Bàrbara (Vall Fosca)',1613,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/santa-barbara-vall-fosca/'),
('santa-fe','Santa Fe',1211,'Alt Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/santa-fe/'),
('santa-magdalena','Santa Magdalena',526,'Alt Empordà',false,'https://www.feec.cat/activitats/100-cims/cim/santa-magdalena/'),
('santa-magdalena-de-cambrils','Santa Magdalena de Cambrils',1547,'Osona, Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/santa-magdalena-de-cambrils/'),
('serra-de-pinos','Serra de Pinós',928,'Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/serra-de-pinos/'),
('serrat-alt','Serrat Alt',830,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/serrat-alt/'),
('serrat-de-carrasquers','Serrat de Carrasquers',1429,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/serrat-de-carrasquers/'),
('serrat-de-la-madrona','Serrat de la Madrona',682,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/serrat-de-la-madrona/'),
('serrat-de-migdia-serrat-de-picancel','Serrat de Migdia (Serrat de Picancel)',1082,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/serrat-de-migdia-serrat-de-picancel/'),
('serrat-de-sant-isidre','Serrat de Sant Isidre',1117,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/serrat-de-sant-isidre/'),
('serrat-voltor','Serrat Voltor',2282,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/serrat-voltor/'),
('serret-del-cisa','Serret del Cisa',542,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/serret-del-cisa/'),
('sobrepuny','Sobrepuny',1653,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/sobrepuny/'),
('taga','Taga',2040,'Ripollès',true,'https://www.feec.cat/activitats/100-cims/cim/taga/'),
('tagamanent','Tagamanent',1056,'Vallès Oriental',true,'https://www.feec.cat/activitats/100-cims/cim/tagamanent/'),
('talaia-del-montmell','Talaia del Montmell',861,'Baix Penedès',true,'https://www.feec.cat/activitats/100-cims/cim/talaia-del-montmell/'),
('torre-alta-castell-ferran','Torre Alta (Castell Ferran)',842,'Anoia',false,'https://www.feec.cat/activitats/100-cims/cim/torre-alta-castell-ferran/'),
('torre-deina','Torre d’Eina',2830,'Cerdanya Nord, Conflent',true,'https://www.feec.cat/activitats/100-cims/cim/torre-deina/'),
('torre-de-goa','Torre de Goà',1267,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/torre-de-goa/'),
('torre-de-la-macana','Torre de la Maçana',794,'Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/torre-de-la-macana/'),
('torre-de-les-conclues','Torre de les Conclues',699,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/torre-de-les-conclues/'),
('torre-de-madeloc','Torre de Madeloc',656,'Rosselló',true,'https://www.feec.cat/activitats/100-cims/cim/torre-de-madeloc/'),
('torre-del-far','Torre del Far',498,'Rosselló',false,'https://www.feec.cat/activitats/100-cims/cim/torre-del-far/'),
('torreneules','Torreneules',2713,'Ripollès',false,'https://www.feec.cat/activitats/100-cims/cim/torreneules/'),
('torres-de-cabrenc','Torres de Cabrenç',1344,'Vallespir',false,'https://www.feec.cat/activitats/100-cims/cim/torres-de-cabrenc/'),
('torreta-de-lorri','Torreta de l’Orri',2436,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/torreta-de-lorri/'),
('torreta-del-cadi','Torreta del Cadí',2562,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/torreta-del-cadi/'),
('torreta-del-montsia','Torreta del Montsià',763,'Montsià',true,'https://www.feec.cat/activitats/100-cims/cim/torreta-del-montsia/'),
('tossa-despinau','Tossa d’Espinau',1087,'Alt Empordà, Garrotxa',false,'https://www.feec.cat/activitats/100-cims/cim/tossa-despinau/'),
('tosa-del-braibal','Tossa del Braibal',2657,'Andorra',false,'https://www.feec.cat/activitats/100-cims/cim/tosa-del-braibal/'),
('tossa-grossa-de-montferri','Tossa Grossa de Montferri',387,'Alt Camp',true,'https://www.feec.cat/activitats/100-cims/cim/tossa-grossa-de-montferri/'),
('tossa-plana-de-lles-pic-de-la-portelleta','Tossa Plana de Lles (pic de la Portelleta)',2905,'Andorra, Cerdanya',true,'https://www.feec.cat/activitats/100-cims/cim/tossa-plana-de-lles-pic-de-la-portelleta/'),
('tossal-bovinar','Tossal Bovinar',2842,'Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-bovinar/'),
('tossal-dengrillo','Tossal d’Engrilló',1072,'Baix Ebre, Terra Alta',true,'https://www.feec.cat/activitats/100-cims/cim/tossal-dengrillo/'),
('tossal-despigol','Tossal d’Espígol',368,'Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-despigol/'),
('tossal-de-bades','Tossal de Badés',1818,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-bades/'),
('tossal-de-balinyo','Tossal de Balinyó',1211,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-balinyo/'),
('tossal-de-codonyac','Tossal de Codonyac',1425,'Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-codonyac/'),
('tossal-de-laliga-la-geganta-adormida','Tossal de l’Àliga (la Geganta Adormida)',1315,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-laliga-la-geganta-adormida/'),
('tossal-de-lalzina','Tossal de l’Alzina',697,'Baix Camp',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-lalzina/'),
('tossal-de-la-baltasana','Tossal de la Baltasana',1201,'Baix Camp, Conca de Barberà',true,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-la-baltasana/'),
('tossal-de-la-creu','Tossal de la Creu',658,'Segarra',true,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-la-creu/'),
('tossal-de-la-moradilla','Tossal de la Moradilla',243,'Segrià',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-la-moradilla/'),
('pic-de-perafita','Tossal de la Truita (Pic de Perafita)',2753,'Andorra, Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/pic-de-perafita/'),
('tossal-de-les-roies-de-cardet','Tossal de les Roies de Cardet',2445,'Alta Ribagorça',true,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-les-roies-de-cardet/'),
('tossal-de-les-viudes','Tossal de les Viudes',1379,'Berguedà, Solsonès',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-les-viudes/'),
('tossal-de-lleto','Tossal de Lletó',1631,'Alt Urgell',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-lleto/'),
('tossal-de-mirapallars','Tossal de Mirapallars',1672,'Noguera, Pallars Jussà',true,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-mirapallars/'),
('tossal-de-montagut','Tossal de Montagut',394,'Baix Ebre, Ribera d''Ebre',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-montagut/'),
('tossal-de-mormur','Tossal de Mormur',326,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-mormur/'),
('tossal-de-sant-jordi','Tossal de Sant Jordi',740,'Noguera',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-sant-jordi/'),
('tossal-de-suro','Tossal de Suró',828,'Segarra',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-de-suro/'),
('tossal-del-mas-de-nadal','Tossal del Mas de Nadal',526,'Segarra',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-del-mas-de-nadal/'),
('tossal-del-puial','Tossal del Puial',1913,'Pallars Sobirà',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-del-puial/'),
('tossal-dels-tres-reis','Tossal dels Tres Reis',1350,'Montsià',true,'https://www.feec.cat/activitats/100-cims/cim/tossal-dels-tres-reis/'),
('tossal-gros-pelat-de-talltendre','Tossal Gros (Pelat de Talltendre)',2256,'Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-gros-pelat-de-talltendre/'),
('tossal-gros-serra-de-sant-gervas','Tossal Gros (Serra de Sant Gervàs)',1546,'Alta Ribagorça, Pallars Jussà',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-gros-serra-de-sant-gervas/'),
('tossal-gros-dalmatret','Tossal Gros d’Almatret',346,'Segrià',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-gros-dalmatret/'),
('tossal-gros-de-vallbona','Tossal Gros de Vallbona',803,'Conca de Barberà, Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/tossal-gros-de-vallbona/'),
('tossal-llisoi','Tossal Llisol',1326,'Berguedà',false,'https://www.feec.cat/activitats/100-cims/cim/tossal-llisoi/'),
('tossau-de-mar','Tossau de Mar',2750,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tossau-de-mar/'),
('tosseta-de-lesquella-pic-de-calm-colomer','Tosseta de l’Esquella (Pic de Calm Colomer)',2869,'Cerdanya, Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/tosseta-de-lesquella-pic-de-calm-colomer/'),
('tosseta-rasa','Tosseta Rasa',1217,'Baix Ebre, Terra Alta',false,'https://www.feec.cat/activitats/100-cims/cim/tosseta-rasa/'),
('tristaina','Tristaina',2878,'Andorra',true,'https://www.feec.cat/activitats/100-cims/cim/tristaina/'),
('tuc-darres','Tuc d’Arres',2163,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-darres/'),
('tuc-dera-entecada','Tuc d’Era Entecada',2269,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-dera-entecada/'),
('tuc-de-baciver','Tuc de Bacivèr',2645,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-baciver/'),
('tuc-de-barlonguera','Tuc de Barlonguèra',2802,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-barlonguera/'),
('tuc-de-crabera','Tuc de Crabèra',2630,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-crabera/'),
('tuc-de-la-comamarja','Tuc de la Comamarja',2562,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-la-comamarja/'),
('tuc-de-la-cometa','Tuc de la Cometa',2445,'Pallars Jussà, Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-la-cometa/'),
('tuc-de-la-contesa','Tuc de la Contesa',2780,'Alta Ribagorça, Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-la-contesa/'),
('tuc-de-la-llanca','Tuc de la Llança',2659,'Pallars Sobirà',true,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-la-llanca/'),
('tuc-de-la-tallada','Tuc de la Tallada',2956,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-la-tallada/'),
('tuc-de-lluca','Tuc de Lluçà',2778,'Alta Ribagorça, Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-lluca/'),
('tuc-de-marimanya','Tuc de Marimanya',2679,'Pallars Sobirà, Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-marimanya/'),
('tuc-de-molieres','Tuc de Molières',3010,'Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-molieres/'),
('tuc-de-parros','Tuc de Parros',2731,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-parros/'),
('tuc-de-ratera','Tuc de Ratera',2861,'Pallars Sobirà, Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-ratera/'),
('tuc-de-ribereta','Tuc de Ribereta',2676,'Alta Ribagorça, Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-ribereta/'),
('tuc-de-salana','Tuc de Salana',2485,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-salana/'),
('tuc-de-sarrahera','Tuc de Sarrahèra',2634,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-sarrahera/'),
('tuc-de-samont','Tuc de Somont',2508,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-de-samont/'),
('tuc-dera-pincela','Tuc dera Pincèla',2536,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-dera-pincela/'),
('tuc-des-armeros','Tuc des Armèros',2534,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-des-armeros/'),
('tuc-des-carants','Tuc des Carants',2791,'Alta Ribagorça',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-des-carants/'),
('tuc-des-monges','Tuc des Monges',2699,'Alta Ribagorça, Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-des-monges/'),
('tuc-deth-plan-deth-ome-vacanera','Tuc deth Plan deth Ome (Vacanera)',2194,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-deth-plan-deth-ome-vacanera/'),
('tuc-deth-port-de-vielha','Tuc deth Port de Vielha',2606,'Val d''Aran',true,'https://www.feec.cat/activitats/100-cims/cim/tuc-deth-port-de-vielha/'),
('tuc-dormidor','Tuc Dormidor',1843,'Conflent',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-dormidor/'),
('tuc-gran-dera-sendrosa','Tuc Gran dera Sendrosa',2703,'Val d''Aran',false,'https://www.feec.cat/activitats/100-cims/cim/tuc-gran-dera-sendrosa/'),
('turo-den-galzeran-o-den-mates','Turó d’en Galzeran o d’en Mates',484,'Maresme, Vallès Oriental',false,'https://www.feec.cat/activitats/100-cims/cim/turo-den-galzeran-o-den-mates/'),
('turo-den-mora-turo-del-carmel','Turó d’en Móra (Turó del Carmel)',266,'Barcelonès',false,'https://www.feec.cat/activitats/100-cims/cim/turo-den-mora-turo-del-carmel/'),
('turo-donofre-arnau','Turó d’Onofre Arnau',131,'Maresme',false,'https://www.feec.cat/activitats/100-cims/cim/turo-donofre-arnau/'),
('turo-de-bell-lloc','Turó de Bell-lloc',1702,'Cerdanya Nord',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-bell-lloc/'),
('turo-de-bellver','Turó de Bellver',1045,'Moianès',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-bellver/'),
('turo-de-can-dolcet','Turó de Can Dolcet',416,'Anoia, Baix Llobregat',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-can-dolcet/'),
('turo-de-lermita','Turó de l’Ermità',595,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-lermita/'),
('turo-de-lescletxa','Turó de l’Escletxa (Turó de Montconill)',447,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-lescletxa/'),
('turo-de-lhome','Turó de l’Home',1706,'Vallès Oriental',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-lhome/'),
('turo-de-les-tres-creus','Turó de la Pola (o de les Tres Creus)',930,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-les-tres-creus/'),
('turo-de-la-torre-o-de-castellnou','Turó de la Torre o de Castellnou',624,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-la-torre-o-de-castellnou/'),
('turo-de-magarola','Turó de Magarola',430,'Barcelonès, Vallès Occidental',true,'https://www.feec.cat/activitats/100-cims/cim/turo-de-magarola/'),
('turo-de-montcada','Turó de Montcada',273,'Vallès Occidental',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-montcada/'),
('turo-de-montgat','Turó de Montgat',40,'Maresme',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-montgat/'),
('turo-de-montsoriu','Turó de Montsoriu',633,'Selva',true,'https://www.feec.cat/activitats/100-cims/cim/turo-de-montsoriu/'),
('turo-de-puigmari','Turó de Puigmarí',233,'Selva',false,'https://www.feec.cat/activitats/100-cims/cim/turo-de-puigmari/'),
('turo-del-mal-pas','Turó del Mal Pas',755,'Bages',false,'https://www.feec.cat/activitats/100-cims/cim/turo-del-mal-pas/'),
('turo-del-pou-den-sala','Turó del Pou d’en Sala',1265,'Osona',false,'https://www.feec.cat/activitats/100-cims/cim/turo-del-pou-den-sala/'),
('turo-del-ros','Turó del Ros',635,'Vallès Occidental',false,'https://www.feec.cat/activitats/100-cims/cim/turo-del-ros/'),
('turo-del-samont','Turó del Samont',1273,'Vallès Oriental',false,'https://www.feec.cat/activitats/100-cims/cim/turo-del-samont/'),
('turo-del-vent','Turó del Vent',442,'Selva',false,'https://www.feec.cat/activitats/100-cims/cim/turo-del-vent/'),
('turo-punco','Turó Punçó',2493,'Alt Urgell, Cerdanya',false,'https://www.feec.cat/activitats/100-cims/cim/turo-punco/'),
('volca-del-croscat','Volcà del Croscat',789,'Garrotxa',false,'https://www.feec.cat/activitats/100-cims/cim/volca-del-croscat/'),
('vulturo','Vulturó',2649,'Alt Urgell',true,'https://www.feec.cat/activitats/100-cims/cim/vulturo/')
on conflict (id) do update set name=excluded.name,height=excluded.height,region=excluded.region,essential=excluded.essential,url=excluded.url;

insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('summit-photos','summit-photos',false,6291456,array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy "Users can read their summit photos" on storage.objects for select to authenticated using (bucket_id='summit-photos' and (storage.foldername(name))[1]=(select auth.uid()::text));
create policy "Users can upload their summit photos" on storage.objects for insert to authenticated with check (bucket_id='summit-photos' and (storage.foldername(name))[1]=(select auth.uid()::text));
create policy "Users can replace their summit photos" on storage.objects for update to authenticated using (bucket_id='summit-photos' and (storage.foldername(name))[1]=(select auth.uid()::text)) with check (bucket_id='summit-photos' and (storage.foldername(name))[1]=(select auth.uid()::text));
create policy "Users can delete their summit photos" on storage.objects for delete to authenticated using (bucket_id='summit-photos' and (storage.foldername(name))[1]=(select auth.uid()::text));


